# Generated by Django 5.0.6 on 2024-07-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='youtube_title',
            field=models.CharField(max_length=255),
        ),
    ]
